### ISSUE TITLE
Automatic backups

### ISSUE THREAD

**Issue by PaulMerk** [jokay/docker-ccu-historian#124]
is there a possibility to configure automatic backups like
 
`database.backup='/path/directory/ccu-historian/backup/%Y-%M-%D-Hist-Backup'`

similar to stand-alone installations ?``

**Comment by jokay** [comment]
Yes, should be possible already by adding the parameter to the **ccu-historian.config** as described on the [README.md](https://github.com/jokay/docker-ccu-historian#configuration).

*"Additional config settings should be made by changing the config file ccu-historian.config within the docker container."*
*"It is easier to export the config folder out of the docker container and edit the file there."*

**Comment by jokay** [comment]
@PaulMerk does this work for you?

**Comment by jokay** [comment]
I did test it myself now and can confirm it works:

```sh
...
database.backup='db_%Y-%M-%D-%h.zip'
...
```

Which correctly creates hourly automatic backups:

```sh
...
2021-10-06 20:00:00|INFO   |Creating backup of database to file db_2021-10-06-20.zip
...
```

```sh
...
-rw-r--r-- 1   0   0  19M Oct  6 20:00 db_2021-10-06-20.zip
...
```

Can you retry by adding `.zip` to your config param for `database.backup`?

**Comment by flow4it** [comment]
@jokay Hi, I have a question according to the backup in docker (on QNAP Container station). 
The solution here is not working for me. Every path I set it tells me every day that it was created but I cant find the backup. 

`2022-08-27 00:59:58|INFO   |Creating backup of database to file HistorianBackup_2022-08-27.zip`

Could you tell me where excatly the backup is stored if I use the root path (see above).
And the more important question: Could you explain how I can store the backup outside the container?
What path do I have to set exactly to get out of the container?

Thanks,
flow

**Comment by jokay** [comment]
@flow4it it makes no sense to post on a closed issue which does not correspond to your problem.

Would you mind creating a new issue with the template `Bug report` and fill out some relevant information like your environment, `docker-compose.yml`, `docker run command`, ccu-historian.config` in order to be able to help you?
