### ISSUE TITLE
wrong version in environment variable after update 

### ISSUE THREAD

**Issue by ReinerWatzlawik** [jokay/docker-ccu-historian#141]
I hav done the update from v2.8.1 to 2.8.3. The new version is running and show the version# top right.
The value of the container environment variable 'VERSION' was not set to the new number. 
This is shown in the ccu-historian logfile, the container-overview-screen on DSM and of course the setting page for the environment variables.
So I had to set it manually there.

Because I do not have many expierience with containers my question: Is that correct? 
From other containers (e.g. pihole) I know that a new version automaticaly set the correct version number in corrosponding environment variables.

**Comment by jokay** [comment]
There is an environment variable `VERSION` which is set to **2.8.3** so it may be a problem with your setup?

```sh
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=e0855005370d
CONFIG_HOST_IP=***
CONFIG_HOST_BINRPCPORT=2099
CONFIG_HOST_XMLRPCPORT=2098
CONFIG_CCU_PLUGIN1_TYPE=CUXD
CONFIG_KEEP_MONTHS=12
TZ=Europe/Zurich
CONFIG_CCU_TYPE=CCU3
CONFIG_CCU_IP=***
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
JAVA_VERSION=jdk-11.0.13+8
JAVA_HOME=/opt/java/openjdk
VERSION=2.8.3
HOME=/root
```

**Comment by jokay** [comment]
I'm not sure if you are aware there exists [releases](https://github.com/mdzio/ccu-historian/releases/tag/2.8.3) for DSM 6 and DSM 7 which can be used if you use a Synology NAS?
