### ISSUE TITLE
docker xjokay/ccu-historian stoppt immer sofort automatisch 

### ISSUE THREAD

**Issue by mkeschle** [jokay/docker-ccu-historian#243]
Hi all
ich habe das docker image xjokay/ccu-historian im docker auf synology sowie in einem völlig unabhängig davon aufgesetzten Raspberry PI 3B (1G Ram, 32GB SD Card, mit docker, portainer, keine weiteren containers) aufgesetzt. In beiden Fällen war zwar die Installation des image erfolgreich, ohne Fehlermeldungen, aber der ccu-Historian stoppte am Ende des Startprozesses, d.h. nach jeweils 30'-60', um dann im docker der synology sofort den Startprozess automatisch wieder zu beginnen (auf dem Raspi musste ich manuell re-starten), bis ich diesen Zyklus manuell stoppe. Die Beobachtung ist wiederholbar mit verschiedensten Versuchen.
Ich habe die Folders gem. Instruktionen im portainer gemappt, die ports mal manuell 1 zu 1, mal auch automatisch im portainer (dann im host random-ports) gemappt.
Ich fand bisher noch keinen Grund für den stop, woran könnte das liegen? laufen die anderen instanzen mit dem neuesten image?

- OS: Synology ds718+ mit DSM 7.1.1-42962 Update 2, und auf Raspberry 3B+ Linux raspberrypi 5.15.74-v7+
- Docker version: auf Synology: 20.10.3 1308, auf Raspi: Docker version 20.10.21, build baeda1f
- auf RaspI:  Portainer CE 2.15 (Auf Syno ohne portainer)

Docker Image für xjokay/ccu-historian: latest 30.10.2022

Protokoll-FIle:
[xjokay-ccu-historian1.csv](https://github.com/jokay/docker-ccu-historian/files/9896673/xjokay-ccu-historian1.csv)
anscheinend fehlen environment variablen?

**Comment by jokay** [comment]
Hellu

Schau dir mal das [hier](https://www.cyberdoc-net.de/2020/10/ccu-historian-daten-mit-grafana-visualisieren/) an um die benötigten params für Synology zu setzen.

**Comment by mkeschle** [comment]
Danke, hat funktioniert!
Habe nun aber ein anderes Problem, ccu-Historian löscht mir immer die Dateien der Diagramme in der CCU. Ich eröffne dazu einen neuen issue
