### ISSUE TITLE
Historian macht Diagramm Daten in der CCU unlesbar

### ISSUE THREAD

**Issue by mkeschle** [jokay/docker-ccu-historian#244]
der ccu-Historian macht mir immer die Diagramm-Daten auf dem USB-Stick der CCU (folder usb0/measurement/ ) unslesbar. Die Daten sind weiterhin auf dem Stick, aber die CCU meldet nach der Installation von ccu-Historian sowohl unter der Option Status/Bedienung, Diagramme wie auch unter Einstellungen Diagramme, dass kein USB Stick vorhanden sei. 
Ich kann die Daten wieder nutzen, indem ich sie auf ein anderes Medium kopiere, den Stick neu formattiere (FAT32 oder NTFS) und dann wieder auf den Stick kopiere. Das Kopieren muss ich aber per SFTP Zugriff auf den USB Stick im Raspi (CCU ist raspberrymatic, latest version) kopiere. Wenn ich diese auf den USB Stick im Mac (oder auch am Win10 PC) kopiere scheint es die CCU auch nicht zu finden. 

**To Reproduce**
Dieser Fehler tritt sowohl auf, wenn ich den ccu-Historian als addon in der CCU installiere (finde ich die beste Lösung - eigentlich) oder wenn ich diesen auf der Synology in Docker installiere.

1. Start the container 'jokay/docker-ccu-historian mit parameter gem. Docker.com
2. Execute raspberrymatic, aufruf von Diagramme
3. See error Messdaten für Diagramme sind nicht auffindbar. CCU meldet "kein USB Speicher vorhanden" (od ähnlich)

**Environment (please complete the following information):**

- OS: [e.g. Debian, Windows, ...] raspberrymatic latest version 3.65.11.20221005
- Docker version [e.g. 20.10.3] auf synology Paket, latest version
- Docker compose version [e.g. 1.28.2] n/a

Anm: ich glaube, ich hätte mal das gleiche Problem beobachtet nach einem Zugriff des iobroker auf die CCU, bin aber nicht sicher, ob dies wegen iobroker war oder wegen ccu-Historian. Konnte dies mit iobroker nicht mehr reproduzieren, habe aber mit iobroker auch das Problem, dass das rfd Modull keinen Zugriff erhält (das CuxD Modul findet die Daten hingegen) Dies ist wohl ein ganz anderes Problem, sei hier aber mal erwähnt, ev hat es doch einen Zusammenhang, Zugriffsproblem etc. ...

**Comment by jokay** [comment]
> **To Reproduce** Dieser Fehler tritt sowohl auf, wenn ich den ccu-Historian als addon in der CCU installiere (finde ich die beste Lösung - eigentlich) oder wenn ich diesen auf der Synology in Docker installiere.

Wenn es auch beim AddOn auftritt, ist es m.E. ein mögliches Problem beim [CCU-Historian](https://github.com/mdzio/ccu-historian) selbst.
Bitte beim [CCU-Historian](https://github.com/mdzio/ccu-historian) repo ein issue dafür erstellen, das kann mit dem Docker container so nicht gelöst werden.

Der Docker container läuft aktuell unter dem Benutzer **root**, falls der volume mount korrekt gemacht wurde, sollte es keine Berechtigungsprobleme geben.
Ich muss aber zugeben, dass ich selbst bis jetzt noch nie über ein Synology NAS ein Verzeichnig auf einem USB-Sticks unter Docker gemountet habe. Macht für mich eigentlich auch keinen Sinn, dafür hat man ja den Storage im Synology NAS?
Tritt das Problem mit dem Docker container und einem lokalen Storage mount (nicht USB) auch auf?

**Comment by mkeschle** [comment]
Ja, vermute auch Historian, nicht (nur) das docker package. 
Kleine Korrektur: ich mounte nicht den USB Stick der CCU für die Daten des Historian. Diese gehen sehr wohl in ein Verzeichnis auf dem NAS. Aber ich habe den USB Stick in der CCU für die Funktion „Diagramme“ im WEBUI der CCU, welche m.E. unabhängig von jeglichem Historian oder ioBroker oder dergleichen funktionieren.

**Comment by jokay** [comment]
Ok, verstehe.

Einen Zusammenhang von CCU-Historian und diesen Diagrammen *(vom CCU selbst erstellt)* kann ich aber nicht wirklich erkennen :wink:

**Comment by mkeschle** [comment]
Umso besser, wenn es unabhängig ist. Ich dachte nur, weiss nicht, wie Historian die Daten aus der CCU holt, ob er dort irgendwie auf eine Datenbank zugreift, die ev auch durch die WEBUI Diagramme genutzt werden. 
Dann bleibt aber die Frage: was könnte das Problem sein, dass Historian den USB Stick für die CCU unlesbar macht, und das sowohl als Historian-addon in der CCU wie als Historian in Docker auf einer anderen Maschine im LAN?

**Comment by jokay** [comment]
Ja, Historian hat seine eigene Datenbank und generiert daraus seine eigenen Diagramme, das funktioniert auch bei deaktivierter Option auf der CCU Web-UI und auch ohne USB-Stick.

Möglicherweise ist die max. Anzahl an Schreibzyklen auf dem USB-Stick demnächst erreicht?

**Comment by jokay** [comment]
> Ich dachte nur, weiss nicht, wie Historian die Daten aus der CCU holt

"Der CCU-Historian verwendet die HomeMatic XML-RPC bzw. BIN-RPC API und die Remote HomeMatic-Script API", siehe [hier](https://www.homematic-inside.de/software/ccu-historian) unter "Umsetzung".

**Comment by mkeschle** [comment]
Danke für die Erläuterungen. 
Ich kann die Probleme mit USB-Stick, Schreibzyklen ausschliessen, da ich auf 3 verschiedenen Sticks, 2 davon ganz neu, von Beginn weg die gleichen Probleme hatte.

**Comment by mdzio** [comment]
Wenn der CCU-Historian entfernt von der CCU (z.B. als Docker auf einem Synology-NAS) ausgeführt wird, spricht er nur über die bereits genannten Schnittstellen mit der CCU. Darüber ist es unmöglich, dass der CCU-Historian aus der Ferne den USB-Stick an der CCU verändert. 

Wenn der CCU-Historian als Add-On auf der CCU installiert wird, verwendet er den USB-Stick zur Ablage seiner Datenbank. Diese liegt in einem separten Verzeichnis getrennt von den Diagrammdaten der CCU. Wenn die CCU meldet, dass kein USB-Stick mehr vorhanden ist, dann kann der CCU-Historian auch nicht mehr funktionieren. Bei mir funktioniert der USB-Stick nach der Add-On-Installation vom CCU-Historian auch weiterhin. Dies muss auch sein, da ansonsten der CCU-Historian nicht mehr arbeitet.

**Comment by mkeschle** [comment]
Danke. Ich habe den historian mittlerweile auf der Synology NAS in docker installiert, funktioniert seit 2 Wochen problemlos. Ich schliesse somit den issue hier
