### ISSUE TITLE
Zeit im Historian (auf docker) um 1 h verschoben? 

### ISSUE THREAD

**Issue by mkeschle** [jokay/docker-ccu-historian#251]
**Describe the bug**
Hallo, bin nicht sicher ob dies ein bug ist oder einfach eine Einstellungssache: ich habe realisiert, dass die Daten im Historian (auf Syno 718, docker) um 1h verschoben sind (i.e. es wird 16h anstelle von 17h angezeigt, etc.)
Das NAS und die Raspberrymatic (seprates Raspi Pi3) zeigen beide die gleiche, aktuelle Systemzeit an

**To Reproduce**
Zeit in ccu-historian Grafiken um 1h verschoben (zu früh)

ccu-histirian grafiken im Webbrowser wie auch auf iOS in der app HistClient

1. Start the container '...'
2. Execute '...'
3. See error

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Debian, Windows, ...]
- Syno 718 mit aktuellem DSM
- Docker version [e.g. 20.10.3]
- aktuelle Dockeversion auf Syno, ccu-historian xjokay-ccu-historian, vor 16 Tagen installiert
- Docker compose version [e.g. 1.28.2]

**Command used to run the container**

- [e.g. docker run -v ...]

**Docker compose file (with passwords redacted)**

```yml
services:
   image: ...
```

**Additional context**

**Comment by jokay** [comment]
Sieht für mich danach aus, dass die Zeit in **UTC** ist, weil die Zeitzone per environment variable `TZ` nicht gesetzt wurde.

**Comment by mkeschle** [comment]
Wow! das ist zeitnaher support! vielen Dank! Ja, der Tipp war richtig, ich hatte sogar in diesen variables TZ = UTC - wohl aus nicht-Wissenheit irgendwo mal abgeschrieben. Jetzt funktioniert's. 
Dieser sunday-real-time-support wäre eine Weinflasche wert! Wenn ich richtig interpretiere sind wir beide in Zürich, melde dich mal in Höngg (Giacomettistrasse 19, Martin Eschle)! :-)
Gruss
Martin

**Comment by jokay** [comment]
Sehr gerne, freut mich dases geht :+1:

**Comment by mkeschle** [comment]
Danke!
