### ISSUE TITLE
docker container xjokay/ccu-historian doesn't shutdown properly

### ISSUE THREAD

**Issue by Vrumf0ndel** [jokay/docker-ccu-historian#318]
**Describe the bug**

I'm using UNRAID with docker _xjokay/ccu-historian_. When trying to stop the container via UI, the UI shows a running cycle for approx. 30 sec and then an error message appear: "Fehler bei der Ausführung". Then a forced shutdown of the container is done.

Root cause:
A shutdown of the docker container doesn't signal the java process to shutdown, it only signals the parent shell process. Shutdown hangs until time limit is reached and remaining processes are killed.

**To Reproduce**

1. Start the container 'xjokay/ccu-historian'
2. Stop the container
3. Wait for timeout.
4. See error message

**Expected behavior**

A graceful shutdown of docker container to prevent any damages to the database.

**Solution proposal**

Add the command "exec" before every java command in entrypoint.sh.
This forces the java process to get PID 1.

Before:
$ ps -elf
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S 99           1     0  0  80   0 -  1745 -      19:22 ?        00:00:00 /bin/bash /usr/local/bin/entrypoint.sh
0 S 99           9     1  3  80   0 - 1555107 -    19:22 ?        00:01:07 java -jar /opt/ccu-historian/ccu-historian.jar -config /opt/c...
4 S 99         550     0  0  80   0 -   654 -      19:59 pts/0    00:00:00 sh
0 R 99         556   550  0  80   0 -  2224 -      19:59 pts/0    00:00:00 ps -elf
$ 

After:
$ ps -elf
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S 99           1     0 99  80   0 - 1727874 -    00:31 ?        00:00:08 java -jar /opt/ccu-historian/ccu-historian.jar -config /opt/c...
4 S 99          64     0  0  80   0 -   654 -      00:31 pts/0    00:00:00 sh
0 R 99          75    64  0  80   0 -  2224 -      00:32 pts/0    00:00:00 ps -elf
$ 

**Environment (please complete the following information):**

- OS: UNRAID 
- Docker version 20.10.5

**Additional context**

When Docker attempts to stop a container, it will send the specified signal to PID 1, the process that Docker starts. Docker will completely ignore any other process running within this container. So that means when we issue a docker stop, the Docker daemon will send a SIGTERM signal to the docker-entrypoint.sh process, not to the running service.

**Comment by Vrumf0ndel** [comment]
I have tested it with a fork of your repo. It works as expected.
https://github.com/vrumf0ndel/docker-ccu-historian/commit/569d0042f134b02d57487c42baab72901083634c

**Comment by jokay** [comment]
I will have a look and check if there are no downsides, when starting it using `exec`.

**Comment by jokay** [comment]
@Vrumf0ndel what about [this](https://github.com/jokay/docker-ccu-historian/pull/319) change, would this work too for you?

**Comment by Vrumf0ndel** [comment]
@jokay Thanks for your very quick response and solution. I will try it and give you feedback.

**Comment by Vrumf0ndel** [comment]
Unfortunately, your proposal doesn't seem to work on my UNRAID server.
When shutdown was triggered, the expected new log entry before exit doesn't appear.
The shutdown still runs into timeout.
I've checked that the file /usr/local/bin/entrypoint.sh contains the changes after docker pull.
But it doesn't have any effect now.

**Comment by jokay** [comment]
Ok, will need to further test then.

I mainly use `docker-compose` where it works to stop the container without problems but I see it can be done better :wink:

**Comment by Vrumf0ndel** [comment]
Just for information: the status of the Docker container shutting down is visible in UNRAID UI and it is 137, which means the SIGKILL was sent after timeout.

**Comment by Vrumf0ndel** [comment]
Übrigens vielen Dank für die schnelle Reaktion mit einer Lösungsidee. Ich habe da auch schon viel schlechtere Erfahrungen mit Projekten hier gemacht und teilweise einige Monate auf Reaktion warten müssen. Absolut top!

**Comment by jokay** [comment]
I tried multiple approaches and the one with `exec` seems to be the best one for now.

https://securedmind.com/post/handling-docker-stop-signals-properly/

I merged the changes and they will be included in the next release, which depends on the official [CCU-Historian](https://github.com/mdzio/ccu-historian) release.

Thank you for your contribution and your patience 👍🏼

**Comment by jokay** [comment]
@Vrumf0ndel the changes are included in the today's release [3.4.0](https://github.com/jokay/docker-ccu-historian/releases/tag/3.4.0).
