### ISSUE TITLE
ccu-historian bleibt im Container während Start hängen - Webserver für UI startet nicht

### ISSUE THREAD

**Issue by Vrumf0ndel** [jokay/docker-ccu-historian#322]
Hallo zusammen.
Ich hänge jetzt schon seit Tagen an einem Problem und finde keine Lösung.
Vielleicht hat hier jemand eine Idee was die Ursache dafür sein kann.

Ich habe ein Upgrade von UNRAID 6.9.2 auf 6.10.3 gemacht (Docker 20.10.5 -> 20.10.14).
Danach habe ich festgestellt, dass der Container xjokay/ccu-historian:3.3.1 zwar gestartet werden kann, aber dann in der Startsequenz hängen bleibt.
Um das Problem zu beheben habe ich wieder ein Downgrade zurück auf UNRAID 6.9.2 gemacht.
Das Problem ist jetzt aber, dass der Container jetzt auch damit nicht mehr richtig startet.

2023-07-19 20:06:41|INFO |xjokay/ccu-historian 3.3.1
2023-07-19 20:06:41|INFO |Starting CCU-Historian using the following config:
|---
|database.dir='/database'
|database.webAllowOthers=true
|devices.device1.address='192.168.1.200'
|devices.device1.type=CCU3
|devices.device1.plugin1.type=CUXD
|devices.historianAddress='192.168.1.100'
|webServer.historianAddress='192.168.1.100'
|webServer.showLastValue=true
|---
2023-07-19 20:06:42|INFO |CCU-Historian V3.3.1
2023-07-19 20:06:42|INFO |(C)MDZ (info@ccu-historian.de)
2023-07-19 20:06:42|INFO |Starting base services
2023-07-19 20:06:42|INFO |Connecting to database
2023-07-19 20:06:43|INFO |Starting database web server
2023-07-19 20:06:43|INFO |Setting up device 1
2023-07-19 20:06:43|INFO |Creating HM script client for http://192.168.1.200:8181/tclrega.exe
2023-07-19 20:06:43|INFO |Setting up plug-in 1
2023-07-19 20:06:43|INFO |Configured following interfaces: BidCos-RF, HmIP-RF, SysVar, CUxD
2023-07-19 20:06:43|INFO |Starting interfaces
2023-07-19 20:06:43|INFO |Starting BIN-RPC server on port 2099
2023-07-19 20:06:43|INFO |Starting XML-RPC server on port 2098

Danach geht es nicht mehr weiter, auch Stunden später tut sich nichts.

Wenn ich den LogLevel auf ALL stelle sehe ich, dass die RPC-Schnittstelle einwandfrei mit der CCU3 kommuniziert.
Aber der Webserver für die UI startet nicht.
Woran kann das liegen?

**Comment by Vrumf0ndel** [comment]
Ich habe das in einer VM mit Ubuntu 22.04 LTS mit Docker 20.10.21 ausprobiert.
Auch da bleibt es ab der gleichen Stelle hängen.
Dann habe ich die Beispiel Konfiguration aus dem Readme ausprobiert mit minimalen Änderungen der Einstellungen (Port 80 ist schon belegt).

docker run -d \
  -v $PWD/data/database:/database \
  -v $PWD/data/config:/opt/ccu-historian/config \
  -p 80:8080 \
  -p 2098:2098 \
  -p 2099:2099 \
  -p 8082:8082 \
  -e TZ=Europe/Berlin \
  -e CONFIG_CCU_TYPE=CCU3 \
  -e CONFIG_CCU_IP=192.168.1.200  \
  -e CONFIG_HOST_IP=192.168.1.100 \
  -e CONFIG_HOST_BINRPCPORT=2099 \
  -e CONFIG_HOST_XMLRPCPORT=2098 \
  -e CONFIG_CCU_PLUGIN1_TYPE=CUXD \
  -e CONFIG_KEEP_MONTHS=12 \
  docker.io/xjokay/ccu-historian:latest

Auch hierbei bleibt es an gleicher Stelle hängen.

**Comment by jokay** [comment]
`-p 80:8080` ist nicht korrekt.

Auf den rechten Seite vom ":" muss zwangsweise "80" stehen.

Auf der linken Seite vom Mapping weiss ich nicht, ob der Port "80" nicht bereits für einen automatischen redirect auf "443" verwendet wird.

Evtl. mal mit `-p 8080:8080` versuchen ob das UI dann mit "http://{host-ip}:8080" erreichbar ist?

**Comment by Vrumf0ndel** [comment]
Danke für die Hilfe. Hatte da die Reihenfolge mit den Ports verwechselt.
Ich habe es nun auch mit anderen Porteinstellungen versucht und es hat einfach nichts funktioniert.

Aus lauter Verzweiflung und Frust habe ich dann doch mal die CC3 neu gestartet... 
...und plötzlich lief alles wieder normal. 

Manchmal hilft es sich an den Leitsatz zu erinnern: "boot tut gut!"

Trotzdem frage ich mich was genau da nicht mehr funktioniert hat. Im Historian Log gab es keinen Hinweis was darauf hingedeutet hätte.
